### ISSUE TITLE
아티클 views 할것

### ISSUE THREAD

**Issue by Jeong1n** [SCC-AI-3/Spartagora_Back#2]
- [x] 메인페이지 데이터보내주기

- [x] 카테고리별 데이터보내주기

- [x] 글쓰기 기능

- [x] 댓글 기능

**Comment by Jeong1n** [comment]
메인페이지 글쓰기기능 추가 2022.07.14

**Comment by Jeong1n** [comment]
카테고리 데이터보내주기 추가

**Comment by 5aim** [comment]
PostMan으로 test 해주시면 감사하겠습니당ㅎㅎ
